eureka:
  instance:
    #心跳
    lease-renewal-interval-in-seconds: 5
    #存活
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    #拉取信息 单位秒
    registry-fetch-interval-seconds: 30
server:
    port: 8003

spring:
    application:
        name: gateway
    http:
      encoding:
        force: true
        charset: utf-8
    cloud:
      gateway:
        routes:
          - id: gateway
            uri: http://localhost:8003
            predicates:
              - Path=/base/**
            filters:
              - StripPrefix=1
          - id: basic
            uri: lb://basic
            predicates:
              - Path=/basic/**
            filters:
              - StripPrefix=1
          - id: auth
            uri: lb://auth
            predicates:
              - Path=/auth/**
            filters:
              - StripPrefix=1
          - id: business
            uri: lb://business
            predicates:
              - Path=/business/**
            filters:
              - StripPrefix=1
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: 'http://localhost:8001/rsa/publicKey' #配置RSA的公钥访问地址
    redis:
      database: 2
      port: 6379
      host: localhost
      password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"
      #swagger
      - "/doc.html"
      - "/webjars/**"
      - "/swagger-resources/**"
      - "/favicon.ico"
      - "/service-worker.js"
      - "/base/v2/**"
      - "/basic/v2/**"
      - "/business/v2/**"