eureka:
  instance:
    #心跳
    lease-renewal-interval-in-seconds: 5
    #存活
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    #拉取信息 单位秒
    registry-fetch-interval-seconds: 30
server:
    port: 8009
spring:
    application:
        name: basic
    http:
      encoding:
        force: true
        charset: utf-8

    redis:
      database: 2
      host: localhost
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      timeout: 3000ms
    profiles:
      active: dev


swagger.enabled: false